name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches: [ main ]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure build dir exists
        run: mkdir -p build

      - name: Copy images directory (if exists)
        run: if [[ -d img ]]; then cp -R img build/img; fi

      # - name: Marp Build (README)
      #   uses: docker://marpteam/marp-cli:v3.0.2
      #   with:
      #     args: README.md -o build/index.html
      #   env:
      #     MARP_USER: root:root

      # - name: Marp Build (README.pdf)
      #   uses: docker://marpteam/marp-cli:v3.0.2
      #   with:
      #     args: README.md --allow-local-files -o build/README.pdf
      #   env:
      #     MARP_USER: root:root

      # - name: Marp Build (README.pptx)
      #   uses: docker://marpteam/marp-cli:v3.0.2
      #   with:
      #     args: README.md --allow-local-files -o build/README.pptx
      #   env:
      #     MARP_USER: root:root

      - name: Check if docs folder exists
        id: docs-folder-exists
        run: bash -c "[[ -d docs ]] ; echo \"has_docs=\$?\" >> \"$GITHUB_OUTPUT\""

      - name: Marp Build (docs folder, if exists)
        if: steps.docs-folder-exists.outputs.has_docs == '0'
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: -I docs/ -o build/docs/
        env:
          MARP_USER: root:root

      - name: Marp Build pptx (docs folder, if exists)
        if: steps.docs-folder-exists.outputs.has_docs == '0'
        uses: docker://marpteam/marp-cli:v3.0.2
        with:
          args: --pptx --allow-local-files --image-scale 2 -I docs/ -o build/docs/
        env:
          MARP_USER: root:root
      
      - name: make index
        if: steps.docs-folder-exists.outputs.has_docs == '0'
        run: |
              #! /bin/bash

              cd build
              
              cat << HTML > index.html
              <!DOCTYPE html>
              <html lang="ja-JP">
              <head>
                <meta charset="utf-8">
                <title>PRESENTATIONS</title>
              </head>
              <body>
              <h1>プレゼンテーションアーカイブ</h1>
              <ul>
              HTML

              for file in `find -name "*.html" -not -name "index.html" | sed 's/\.html//g'`; do

                title=`grep "<h1" $file.html | sed 's@<h1 id=".*">\(.*\)</h1>@\1@g' |head -n1`
                title=${title:-`echo $file | rev | cut -d '/' -f 1 | cut -d '.' -f2- | rev`}

                echo -e "$file\t\t$title"

                cat << HTML >> index.html
                <li>
                  <a href="$file.html" target="_blank">$title</a>
                  <span>
                    [<a href="$file.pptx" target="_blank">pptx</a>]
                  </span>
                </li>
              HTML
              done

              cat << HTML >> index.html
              </ul>
              </body>
              </html>
              HTML

      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/